version: 2
updates:
  # version updates: enabled
  # security updates: enabled
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: "daily"
