name: Build Images
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Setup Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_CLI_TOKEN }}

    - name: Build and Push
      uses: docker/bake-action@v2
      env:
        TAGS: "latest,${{ github.ref_name }}"
        REGISTRY: "natsio"
      with:
        push: true
